defaults: &defaults
  adapter: postgresql
  template: template0

development:
  <<: *defaults
  username: "lporras"
  database: "notes_development"

test:
  adapter: jdbcsqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000